
unquoted_constants = {'RC_VISIBLE', 'LIQUID', 'S_DRAW', 'TEMP', 'GAS', 'SUPPRESSATTACK', 'SOLID', 'RC_SCALE', 'VHFCS', 'MOB_LAYER', 'ONE_ATMOSPHERE', 'FPRINT', 'CONDUCT', 'IV_DRAW', 'EXTRADELAY', 'IV_INJECT', 'ONBELT', 'TO_SELF', 'NOSPLASH', 'RC_FULLNESS', 'TABLEPASS', 'RC_SPECTRO', 'OPENCONTAINER', '-INFINITY', 'INFINITY'}
